### PR TITLE
ayy lmao

### PR DESCRIPTION
**Pull request by Cheridan**
:small_orange_diamond: :large_orange_diamond: :orange_book: :large_orange_diamond: :small_orange_diamond:

### CODE REVIEW

**Comment by Cheridan** [comment]
oh god how did i get here i am not good with comptuer :computer:

**Comment by RemieRichards** [comment]
What are you two up to?

**Comment by Cheridan** [comment]
Don't mind me, just making sure his master is kept up-to-date!!

**Comment by RemieRichards** [comment]
secretses.

**Comment by Cheridan** [comment]
W-why are you checking up on us anyway, hmmm?

**Comment by RemieRichards** [comment]
I'll give you the honest answer: You're my link to vgstation (who are simultaneously my link to baystation) since i like to observe PRs.

It used to be aran but since his profile went hidden I had to find somebody else, that ended up being you.

So suddenly when you get a fork of Orange's repo I got suspicious of shenanigans 

And that's the truth :3

**Pull request merged**
